version: '3.8'

services:
  k6:
    image: grafana/k6:latest
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - ALERT_EMAIL_USER=${ALERT_EMAIL_USER}
      - ALERT_EMAIL_PASS=${ALERT_EMAIL_PASS}
    command: run /app/tests/PMTChatbotResponseTime.js
    # To run all tests, use the Node.js runner instead
    # command: sh -c "npm ci && node run-async-k6.js"

  # Node runner service - use this to run the full test suite with reporting
  node-runner:
    image: node:18-alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - ALERT_EMAIL_USER=${ALERT_EMAIL_USER}
      - ALERT_EMAIL_PASS=${ALERT_EMAIL_PASS}
    command: >
      sh -c "apk add --no-cache curl ca-certificates &&
             curl -L https://example.com -o k6.tar.gz &&
             tar -xzf k6.tar.gz &&
             mv k6-v0.47.0-linux-amd64/k6 /usr/local/bin/k6 &&
             rm -rf k6-v0.47.0-linux-amd64 k6.tar.gz &&
             npm ci &&
             node run-async-k6.js"